env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - warn
    - always
  no-unused-vars:
    - warn
  no-console: 0
  no-constant-condition: 0
