os:
  # - osx
  - linux
sudo: false
cache: yarn
services:
  - mongodb
language: node_js
node_js:
  - stable
  - 7
  - 8
  - 9
install:
  - yarn
before_script:
  - sleep 15
  - mongo twi-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - yarn run ci
