app:
  host: https://stories.octetstream.ru
  # port: 3012
  # env: production
  enableSignup: false
# database:
#   name: ponyfiction
#   user: dark_an
#   pass: j3yHuwibkAKH9bKpBwZlS
session:
  secret: JLhBIVv9PdTpH81XaWSdIxpITcaTZ4IjdmINwhHBo
smtp:
  port: 465
  secure: true
  host: smtp.yandex.ru
  user: noreply@octetstream.ru
  pass: kUj3yHuwibkAKH9bKpBwZlSkTaJLxpITcaT
